### ISSUE TITLE
Auto save ?

### ISSUE THREAD

**Issue by davidleee** [PolarisChen/Piece#1]
Sometimes I would like to restart Piece, and turns out the content is not what I expect.

Since I don't know whether ctrl+s works as saving, will you add an Auto-save function?

**Comment by pol-chen** [comment]
What's the version of your Piece?

Auto-save feature should have been added since v1.1.0. Piece would save your content automatically once you have changed your content, like inserting and deleting.

**Comment by davidleee** [comment]
The version of my Piece is v2.0.1.

Maybe it ran into a crash some time earlier which I am not very sure. The content lost only happened once, and everything works just fine after that.

Anyhow, it's such a relief to know Piece has Auto-save.
Thanks.
